"""histo patch classification package."""

from .config import (
    AppConfig,
    SeedConfig,
    config_to_dict,
    default_config_path,
    load_config,
    parse_config_dict,
    project_root,
    save_config,
)
from .data import (
    Batch,
    DataModule,
    DataModuleConfig,
    DatasetSplit,
    IDCPatchDataset,
    ImageSchema,
    LoaderSchema,
    PatchExample,
    PatchRecord,
    SplitSchema,
    TransformRegistry,
    build_data_module,
    collate_patch_examples,
    discover_records,
    split_by_patient,
)
from .engine import (
    EpochResult,
    EvaluationResult,
    Evaluator,
    EvaluatorConfig,
    PhaseResult,
    PredictionResult,
    TrainSummary,
    Trainer,
    TrainerConfig,
)
from .model import (
    IDCResNetClassifier,
    ModelConfig,
    build_resnet,
    build_model,
)

__all__ = [
    "AppConfig",
    "Batch",
    "DataModule",
    "DataModuleConfig",
    "DatasetSplit",
    "EpochResult",
    "EvaluationResult",
    "Evaluator",
    "EvaluatorConfig",
    "IDCPatchDataset",
    "IDCResNetClassifier",
    "ImageSchema",
    "LoaderSchema",
    "ModelConfig",
    "PatchExample",
    "PatchRecord",
    "PhaseResult",
    "PredictionResult",
    "SeedConfig",
    "SplitSchema",
    "TrainSummary",
    "Trainer",
    "TrainerConfig",
    "TransformRegistry",
    "build_data_module",
    "build_resnet",
    "build_model",
    "collate_patch_examples",
    "config_to_dict",
    "default_config_path",
    "discover_records",
    "load_config",
    "parse_config_dict",
    "project_root",
    "save_config",
    "split_by_patient",
]
