"""histo patch classification package."""

from .data import (
    Batch,
    DataModule,
    DataModuleConfig,
    DatasetSplit,
    IDCPatchDataset,
    ImageSchema,
    LoaderSchema,
    PatchExample,
    PatchRecord,
    SplitSchema,
    TransformRegistry,
    build_data_module,
    collate_patch_examples,
    discover_records,
    split_by_patient,
)
from .engine import (
    EpochResult,
    EvaluationResult,
    Evaluator,
    EvaluatorConfig,
    PhaseResult,
    PredictionResult,
    TrainSummary,
    Trainer,
    TrainerConfig,
)
from .model import (
    IDCResNetClassifier,
    ModelConfig,
    ResNetBackboneRegistry,
    build_model,
)

__all__ = [
    "Batch",
    "DataModule",
    "DataModuleConfig",
    "DatasetSplit",
    "EpochResult",
    "EvaluationResult",
    "Evaluator",
    "EvaluatorConfig",
    "IDCPatchDataset",
    "IDCResNetClassifier",
    "ImageSchema",
    "LoaderSchema",
    "ModelConfig",
    "PatchExample",
    "PatchRecord",
    "PhaseResult",
    "PredictionResult",
    "ResNetBackboneRegistry",
    "SplitSchema",
    "TrainSummary",
    "Trainer",
    "TrainerConfig",
    "TransformRegistry",
    "build_data_module",
    "build_model",
    "collate_patch_examples",
    "discover_records",
    "split_by_patient",
]
